### ISSUE TITLE
Python 3.6.8 → Python 3.7

### ISSUE THREAD

**Issue by cooperpellaton** [cooperpellaton/NachoMemes#1]
Iteration logic in reflow breaks in 3.7

```
Ignoring exception in command meme:
Traceback (most recent call last):
  File "bot.py", line 49, in partition_on
    n = next(i)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/memebot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(args, **kwargs)
  File "bot.py", line 124, in meme
    strings = _reflow_text(text, meme.box_count)
  File "bot.py", line 154, in _reflow_text
    result = [" ".join(l) for l in partition_on(lambda s: s == "/", text)]
  File "bot.py", line 154, in <listcomp>
    result = [" ".join(l) for l in partition_on(lambda s: s == "/", text)]
RuntimeError: generator raised StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/memebot/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/anaconda3/envs/memebot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(ctx.args, **ctx.kwargs)
  File "/home/ubuntu/anaconda3/envs/memebot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: generator raised StopIteration
```

**Comment by ironchefpython** [comment]
fix'd
